export const supportedPrograms = [
    "BA. B.Ed",
    "B.A. Liberal Arts",
    "BA (MC)",
    "M.Sc (MC & DD)",
    "B.Pharma",
    "M.Sc (Bio-Informat)",
    "B.Sc (ES)",
    "M.SC (EM)",
    "B.Tech (CSE)",
    "B.Tech (IT)",
    "B.Tech (ECE)",
    "B.Tech (CSE-AI)",
    "B.Tech (CSE-DS)",
    "LE-B.Tech (CSE)",
    "LE-B.Tech (ECE)",
    "LE-B.Tech (IT)",
    "MCA (SE)",
    "M.Tech (R & A)",
    "M.Tech (CSE)",
    "M.Tech (IT)",
    "M.Tech (ECE)",
    "M.Tech (ECE-W)",
    "M.Tech (CSE) (W)",
    "M.Tech (CE)",
    "MA (Eng)",
    "BA (Eng)-4 Year",
    "BA (Eco)-4 Year",
    "MA (Eco)",
    "MBA",
    "MBA (Analytics)",
    "MBA (FA)",
    "MBA (Weekend)",
    "BBA",
    "B.Com (H)",
    "B.Tech (Bio-Tech)",
    "M.Tech (Bio-Tech)",
    "M.Tech (FPT)",
    "M.Tech (IBT)",
    "B.Sc (Phyiscs)",
    "B.Sc (Chemistry)",
    "B.Sc (Mathematics)",
    "B.Arch",
    "M.Arch",
    "M.Plan",
    "B.Design",
    "LE-B.Design",
    "M.Design",
    "B.Tech (AI & DS)",
    "B.Tech (AI & ML)",
    "B.Tech (A & R)",
    "B.Tech (IIOT)",
    "LE-B.Tech (AI & DS)",
    "LE-B.Tech (AI & ML)",
    "LE-B.Tech (A & R)",
    "LE-B.Tech (IIOT)",
    "B.Tech (CE)",
    "B.Tech (Energy)",
    "LE-B.Tech (CE)",
    "MBA (DM)",
    "MBA (FIS)",
    "LE-MBA (FIS)",
    "PGDFLSA",
    "BA LLB",
    "BBA LLB",
    "LLM (ADR)",
    "LLM (CJS)",
    "LLM (IPR)",
    "LLM (II PL)",
    "LLM (CL CC)",
    "LLM (CL)",
    "MA (MC)",
    "M.Ed",
];